{%set name = "webassets" %}
{%set version = "0.12.1" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "e7d9c8887343123fd5b32309b33167428cb1318cdda97ece12d0907fd69d38db" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  entry_points:
    - nwebassets = webassets.script:run
  number: {{ build_num }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - webassets
    - webassets.bundle
    - webassets.cache
    - webassets.env
    - webassets.exceptions
    - webassets.importlib
    - webassets.loaders
    - webassets.merge
    - webassets.script

  commands:
    - nwebassets --help

about:
  home: https://github.com/miracle2k/webassets/
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'Media asset management for Python, with glue code for various web frameworks'
  doc_url: https://webassets.readthedocs.io/
  dev_url: https://github.com/miracle2k/webassets/

extra:
  recipe-maintainers:
    - pmlandwehr
