{% set name = "webassets" %}
{% set version = "2.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "167132337677c8cedc9705090f6d48da3fb262c8e0b2773b29f3352f050181cd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  entry_points:
    - nwebassets = webassets.script:run
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - webassets
    - webassets.bundle
    - webassets.cache
    - webassets.env
    - webassets.exceptions
    - webassets.importlib
    - webassets.loaders
    - webassets.merge
    - webassets.script

  commands:
    - nwebassets --help

about:
  home: https://github.com/miracle2k/webassets/
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'Media asset management for Python, with glue code for various web frameworks'
  doc_url: https://webassets.readthedocs.io/
  dev_url: https://github.com/miracle2k/webassets/

extra:
  recipe-maintainers:
    - pmlandwehr
