travis:
  secure:
    BINSTAR_TOKEN: tOblFzkHX8j/bDoLzZgbhrWkumjO35NEV5q+4H5kgf7x2m507YCp3hyS10dAJEfh87B5SsW3Oy2Y1VU2GyjwNGsBDp6AHvo8wOXrPvceVJRF/ZgRY8//jZCvr9HOFRi179ZEwbtG1197ua3umblGmJ6K5TtmnQBSQS6QXQD1w28SXI1IzxCwXvsKftnzhY9qMmIccWD1z6i7uQVy86svCwIyFWv27kvwWYnAo9NS3bzRi5Gvx/p7NmhqlQiQnKATLpN0h3HoIWMM60dJQGMfLAn0yneHR/cvB0Lb2Ene9eezAaNrwHK4fdYKYpcSo5kwJlmR9TCEnwJmX0s+u6VaFpNKdY6npFE26WiqmxFdKxkc8G9FiKyDpxITdcumE/jldvXDk56I6FJHJ1ydyyf/McbF8LktRnkCNBF8F/hQ4e+BWVflvb96oZUvvX4QON9kroM6FmehBn2Dhy7t3vwfUuiKD7zRnim5cJsFD3pGMys4l/6yUAUNgJHQvZT0Wa6pft2hQrNDDun7nceBa+skt0SCMn5seczrZ7dQOGaUUk98AgNZgKyn1+xmxic71ZG4H+wjYdyfeNxfmA4jPa6gUyrhTvoowKF3x4olBT1XCv9GFwy0xwKN7oUVp7hlv6pQlzyVsN7he/+sM4u+Bp7nAi2eg2nW2E5VpoUxLMjrDD4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
