travis:
  secure:
    BINSTAR_TOKEN: Fd75Lt7OAVRLt7W79ZnwAUrwOWtNGPCXPLc83SJCsdHl46HV9KIQLjwADwqt2fSuv8M/FuPBBT+u6AFTL2qxe15AdEeMSUBkP6HxQGrENBs6npPamLpmtskY+f5Pj6ZakIXbe0pKHZRGlkr71xYeK1owe1dNF97JBbuLNUDlxY/3gH5J9EOx6Ey+JRIgXAp0pKju9Z/KWXUFMdaYDrG7YjaLhIFNCIfcmSviGAp/SecdSRwCtRq5BJ4L2sdVWg55ki9osC/uGCMrf1NWd/9FCCMKDMPRie+vpNxgFGQc5Y56cTDjDpB3ByNpdRiYq9GDfhuNlZCwtyPjzpUd8xsz522SWyupSXfn4hrkBXoMrvrNi7Png5Wkn/05rDIqxjD1ghk4rFZ2gK0j3LGck71LRAU4AU7rFxuRQGa3y9nYsvFDMWst1kiPseFOkqdObxr5RmKUQIBv0Gnj1Ym3JutlvjiEi9/MKqT1ZhMpopKv6XBLk/h7jmPfn0Ync15LDiw8Cv08LnUVHFPwjIEnCe5/qzi4iiCVeQ+yAK9zNGockCRdeXJst6xzwYRWFLYgIOpEkBFccFxppVL4Pgwb1FsAqoFh4b6EN9DkZHTAB4x8Q2QzXWcmvnkk/NPcein2tJJI3LcMURfhujPq0DaBGhIoMXKueAnzKm9fR+IjwVFxgXk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
