travis:
  secure:
    BINSTAR_TOKEN: fyxK0+pN35BmfiCzNbyozmt8WcvNHvAj+ErkiNMbqSC7efMfsK+Nx0OxGjAw5n7Pirs2m+GQNo1LAH4ph6CVQYk0158pwgXTK0LoCvmn5OO2UMF9aFqiFo5Q/Ts5kguIU5VTJ9qYDNDt5C8u9Xd7BmJ48bMBUMUmoIItHBKFY9Ye2Mo+QufAKyIYsh2XgR2oPFG7FNzAWNY6JYvc7fEuGD5hmI559IG2aRRI2DVPBMjPWkACuhcApN9tX29MHoV1vsoABs/OBjlRRmXyoP59IW9NXURD7VRHk7Vw0aWZ7qccnmuJ8Fys8nNxzajIrZrE5lWGE4+z+b1p4FdOe2FLdKmnfCmM35CVneHrQyeRVjutDfl9spYKf26MPq6ofcC1VJT3o/SG0ceQ+/lVQji08PplOLlJN1wMEZe9t0R4uLJroPu1OaQTXR1Ep7Rw6L0bgxhHAWWHTrJk8OpE9Yms0kOr4YOdjU0Oz+Opa0iBWNPfeHHPlYRFDOmXpvZFIJqb37l4mNhOzowAkIX2jLBFf8pyKtItWk0spQcS4/Iz28ITJopDMOe63Q3CeUXUgtvTJSPlDoRAw7WjWXAYRcMziGddtIC0a66SKV2069Dr5SqOMJo74QDdi/9ABM6emt4rnZPgyogehIkb6dav4GyiXzVHyoMUgG7lPSkbMpIZJ5s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
